Repository ZenBit-Tech/code-lions_be, pull requests merged in 2024-05, with the labels that each got.

#1 fix: template
  .env.example
  .eslintrc.js
  docker-compose.yml
  package-lock.json
  package.json
  src/app.controller.ts
  src/app.module.ts
  src/common/entities/user.entity.ts
  src/common/filters/http-exception.filter.ts
  src/main.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
Labels: good first issue

#3 Feat/user registration
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/common/ErrorResponse.ts
  src/common/errors.ts
  src/common/filters/http-exception.filter.ts
  src/common/responseDescriptions.ts
  src/filters/httpException.filter.ts
  src/main.ts
  src/modules/users/DTO/create.dto.ts
  src/modules/users/DTO/response.dto.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.spec.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.spec.ts
  src/modules/users/users.service.ts
Labels: documentation, feature, test

#2 Feat/mailer + eslint fixes
  .env.example
  .eslintrc.js
  .github/pull_request_template.md
  nest-cli.json
  package-lock.json
  package.json
  src/app.module.ts
  src/common/filters/http-exception.filter.ts
  src/filters/httpException.filter.ts
  src/main.ts
  src/modules/auth/auth.module.ts
  src/modules/mailer/mailer.config.ts
  src/modules/mailer/mailer.module.ts
  src/modules/mailer/mailer.service.ts
  src/modules/mailer/mailer.types.ts
  src/modules/mailer/templates/verify-email.hbs
  src/modules/users/DTO/create.dto.ts
  src/modules/users/DTO/response.dto.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.spec.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.spec.ts
  src/modules/users/users.service.ts
  tsconfig.json
Labels: feature, chore
