Repository ZenBit-Tech/code-lions_be, pull requests merged in 2024-06, with the labels that each got.

#4 Add User Registration with Email OTP Verification
  .env.example
  .husky/pre-commit
  package-lock.json
  package.json
  src/common/error-response.ts
  src/common/errors.ts
  src/common/filters/http-exception.filter.ts
  src/common/response-descriptions.ts
  src/config.ts
  src/filters/http-exception.filter.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/jwt.strategy.ts
  src/modules/users/dto/create.dto.ts
  src/modules/users/dto/public-user.dto.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.spec.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.spec.ts
  src/modules/users/users.service.ts
Labels: feature, chore

#5 Feat/auth verification
  .eslintrc.js
  src/common/errors.ts
  src/config.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/id.dto.ts
  src/modules/auth/dto/tokens.dto.ts
  src/modules/auth/dto/verify-otp.dto.ts
  src/modules/mailer/templates/resend-otp.hbs
  src/modules/mailer/templates/verification-success.hbs
  src/modules/users/dto/public-user.dto.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.service.ts
Labels: enhancement, feature

#6 Login, Password Reset endpoints
  src/common/errors.ts
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/email.dto.ts
  src/modules/auth/dto/login.dto.ts
  src/modules/auth/dto/reset-otp.ts
  src/modules/auth/dto/user-with-tokens.dto.ts
  src/modules/mailer/templates/forgot-password.hbs
  src/modules/users/dto/create-user.dto.ts
  src/modules/users/dto/create.dto.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
Labels: enhancement, feature

#8 feat/implemented user sign up and sign in via google
  .env.example
  package-lock.json
  package.json
  src/common/errors.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/google-payload.dto.ts
  src/modules/auth/google-auth.guard.ts
  src/modules/users/dto/create-user-via-google.dto.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.service.ts
Labels: documentation, feature

#9 Feat/user roles
  package-lock.json
  package.json
  src/common/errors.ts
  src/main.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.guard.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/password.dto.ts
  src/modules/auth/dto/refresh-token.dto.ts
  src/modules/auth/dto/user-response.dto.ts
  src/modules/auth/dto/user-with-tokens-response.dto.ts
  src/modules/auth/strategies/jwt.strategy.ts
  src/modules/roles/role.enum.ts
  src/modules/roles/roles.decorator.ts
  src/modules/roles/roles.guard.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
Labels: enhancement, feature

#10 feat: updated users table, created endpoints
  package-lock.json
  package.json
  src/common/errors.ts
  src/config.ts
  src/modules/auth/dto/user-response.dto.ts
  src/modules/users/dto/update-user-phone.dto.ts
  src/modules/users/dto/update-user-role.dto.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
  uploads/avatars/file-1718301871158-882823500.jpg
Labels: enhancement

#11 feat/implemented soft user deletion and getting users from admin panel
  src/common/errors.ts
  src/config.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/user-response.dto.ts
  src/modules/mailer/templates/soft-delete.hbs
  src/modules/roles/role.enum.ts
  src/modules/users/order.enum.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
Labels: documentation, enhancement, feature

#12 Feat/new profile address
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/common/errors.ts
  src/config.ts
  src/modules/auth/dto/user-response.dto.ts
  src/modules/geoNames/geoNames.controller.ts
  src/modules/geoNames/geoNames.module.ts
  src/modules/geoNames/geoNames.service.ts
  src/modules/users/dto/update-user-address.dto.ts
  src/modules/users/user-id.guard.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
Labels: enhancement

#13 Feat/user profile endpoints
  src/common/errors.ts
  src/config.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/user-response.dto.ts
  src/modules/mailer/templates/suspend-account.hbs
  src/modules/users/dto/personal-info.dto.ts
  src/modules/users/dto/update-user-card.dto.ts
  src/modules/users/dto/update-user-profile-admin.dto.ts
  src/modules/users/dto/update-user-profile.dto.ts
  src/modules/users/dto/user-card.dto.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
Labels: documentation, enhancement, feature

#14 Feat/new profile size card
  src/common/errors.ts
  src/main.ts
  src/modules/auth/dto/user-response.dto.ts
  src/modules/roles/role-user.enum.ts
  src/modules/users/dto/update-user-address.dto.ts
  src/modules/users/dto/update-user-role.dto.ts
  src/modules/users/dto/update-user-size.dto.ts
  src/modules/users/onboarding-steps.enum.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
Labels: enhancement

#15 Feat/public profile endpoints
  src/app.module.ts
  src/common/errors.ts
  src/config.ts
  src/modules/auth/dto/user-response.dto.ts
  src/modules/reviews/dto/create-review.dto.ts
  src/modules/reviews/review-creator.guard.ts
  src/modules/reviews/review.entity.ts
  src/modules/reviews/reviews.controller.ts
  src/modules/reviews/reviews.module.ts
  src/modules/reviews/reviews.service.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
Labels: documentation, enhancement, feature

#16 Fix/sprint2
  .eslintrc.js
  .gitignore
  src/common/errors.ts
  src/config.ts
  src/modules/auth/dto/user-response.dto.ts
  src/modules/users/dto/update-user-address.dto.ts
  src/modules/users/onboarding-steps.enum.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
  uploads/avatars/file-1718301871158-882823500.jpg
Labels: fix

#17 feat/added endpoint to get user by id
  src/modules/reviews/review.entity.ts
  src/modules/reviews/reviews.service.ts
  src/modules/users/users.controller.ts
Labels: documentation, enhancement
