Repository ZenBit-Tech/code-lions_be, pull requests merged in 2024-07, with the labels that each got.

#18 Feat/products
  .eslintrc.js
  package-lock.json
  package.json
  src/app.module.ts
  src/common/errors.ts
  src/config/index.ts
  src/config/typeorm.ts
  src/db/data-source.ts
  src/db/migrations/1719584047941-migrations.ts
  src/db/seeds/color.seeder.ts
  src/db/seeds/index.ts
  src/modules/products/dto/create-product.dto.ts
  src/modules/products/dto/product-response.dto.ts
  src/modules/products/dto/update-product.dto.ts
  src/modules/products/entities/category.enum.ts
  src/modules/products/entities/color.entity.ts
  src/modules/products/entities/colors.type.ts
  src/modules/products/entities/image.entity.ts
  src/modules/products/entities/product-types.enum.ts
  src/modules/products/entities/product.entity.ts
  src/modules/products/entities/styles.enum.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.module.ts
  src/modules/products/products.service.spec.ts
  src/modules/products/products.service.ts
  src/modules/reviews/review.entity.ts
  src/modules/reviews/reviews.service.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.service.ts
Labels: feature

#20 Feat/single product endpoints
  src/app.module.ts
  src/common/errors.ts
  src/modules/cart/cart.controller.ts
  src/modules/cart/cart.entity.ts
  src/modules/cart/cart.module.ts
  src/modules/cart/cart.service.spec.ts
  src/modules/cart/cart.service.ts
  src/modules/cart/response-cart.dto.ts
  src/modules/products/entities/product.entity.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.service.spec.ts
  src/modules/products/products.service.ts
  src/modules/reviews/reviews.controller.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.service.ts
  src/modules/wishlist/wishlist.controller.ts
  src/modules/wishlist/wishlist.entity.ts
  src/modules/wishlist/wishlist.module.ts
  src/modules/wishlist/wishlist.service.spec.ts
  src/modules/wishlist/wishlist.service.ts
Labels: documentation, enhancement, feature

#19 feat: created filters for home page
  src/config/index.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.service.spec.ts
  src/modules/products/products.service.ts
Labels: enhancement

#24 Feat/product feed
  src/mocks/mock-product.ts
  src/modules/products/dto/product-response.dto.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.service.spec.ts
  src/modules/products/products.service.ts
  src/modules/wishlist/wishlist.service.ts
Labels: feature

#23 Feat/product list vendor
  src/common/errors.ts
  src/config/index.ts
  src/mocks/mock-product.ts
  src/modules/cart/cart.service.ts
  src/modules/mailer/templates/approve-product.hbs
  src/modules/mailer/templates/delete-product-admin.hbs
  src/modules/mailer/templates/reject-product.hbs
  src/modules/products/dto/product-response.dto.ts
  src/modules/products/dto/products-count-response.dto.ts
  src/modules/products/entities/product-status.enum.ts
  src/modules/products/entities/product.entity.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.module.ts
  src/modules/products/products.service.spec.ts
  src/modules/products/products.service.ts
  src/modules/wishlist/wishlist.service.spec.ts
  src/modules/wishlist/wishlist.service.ts
Labels: documentation, enhancement, feature

#21 feat: created endpoint to fetch best vendors for best vendors page
  src/common/errors.ts
  src/config/index.ts
  src/modules/users/best-vendors.controller.ts
  src/modules/users/dto/get-best-vendors.dto.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
Labels: documentation, feature

#26 Feat/add product
  .gitignore
  src/common/errors.ts
  src/config/index.ts
  src/main.ts
  src/mocks/mock-product.ts
  src/modules/products/dto/product-response.dto.ts
  src/modules/products/dto/update-product.dto.ts
  src/modules/products/entities/brands.entity.ts
  src/modules/products/entities/category.enum.ts
  src/modules/products/entities/image.entity.ts
  src/modules/products/entities/materials.enum.ts
  src/modules/products/entities/product-types.enum.ts
  src/modules/products/entities/product.entity.ts
  src/modules/products/products.controller.ts
  src/modules/products/products.module.ts
  src/modules/products/products.service.ts
  src/modules/wishlist/wishlist.service.ts
Labels: enhancement, feature

#27 fix: make a mapProducts util function
  src/mocks/mock-product.ts
  src/modules/products/products.service.ts
  src/modules/products/utils/mapProducts.ts
  src/modules/products/utils/sortImages.ts
  src/modules/users/users.service.ts
Labels: hotfix

#28 Feat: chat entities and chat controller with two requests
  package-lock.json
  package.json
  src/app.module.ts
  src/mocks/mock-product.ts
  src/modules/chat/chat.controller.ts
  src/modules/chat/chat.module.ts
  src/modules/chat/chat.service.spec.ts
  src/modules/chat/chat.service.ts
  src/modules/chat/dto/chat-room-response.dto.ts
  src/modules/chat/dto/chat-user.dto.ts
  src/modules/chat/dto/message-response.dto.ts
  src/modules/chat/entities/chat-room.entity.ts
  src/modules/chat/entities/message.entity.ts
  src/modules/events/events.gateway.spec.ts
  src/modules/events/events.gateway.ts
  src/modules/events/events.module.ts
  src/modules/users/user.entity.ts
Labels: documentation, question, feature, dependencies

#31 Feat/rental rules
  package-lock.json
  package.json
  src/app.module.ts
  src/common/errors.ts
  src/common/utils/getDateWithoutTime.spec.ts
  src/common/utils/getDateWithoutTime.ts
  src/config/index.ts
  src/mocks/mock-product.ts
  src/modules/auth/auth.service.ts
  src/modules/auth/dto/user-response.dto.ts
  src/modules/cart/cart.module.ts
  src/modules/cart/cart.service.ts
  src/modules/cart/response-cart.dto.ts
  src/modules/mailer/templates/account-deactivated.hbs
  src/modules/mailer/templates/account-reactivated.hbs
  src/modules/mailer/templates/low-rating-warning.hbs
  src/modules/products/dto/product-response.dto.ts
  src/modules/reviews/reviews.module.ts
  src/modules/reviews/reviews.service.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
  src/modules/wishlist/wishlist.service.ts
Labels: documentation, enhancement, feature

#30 feat: create chat and send message
  src/common/decorators/get-user-id.ts
  src/modules/chat/chat.controller.ts
  src/modules/chat/chat.module.ts
  src/modules/chat/chat.service.ts
  src/modules/chat/dto/chat-room-response.dto.ts
  src/modules/chat/dto/chat-user.dto.ts
  src/modules/chat/dto/create-chat.dto.ts
  src/modules/chat/dto/message-response.dto.ts
  src/modules/chat/dto/send-message.dto.ts
  src/modules/chat/dto/user-typing.dto.ts
  src/modules/events/events.gateway.ts
  src/modules/events/events.module.ts
Labels: documentation, feature

#32 feat: unread messages and mark them as read
  package-lock.json
  src/mocks/mock-product.ts
  src/modules/chat/chat.controller.ts
  src/modules/chat/chat.module.ts
  src/modules/chat/chat.service.ts
  src/modules/chat/dto/create-chat.dto.ts
  src/modules/chat/dto/get-user-chats.dto.ts
  src/modules/chat/dto/index.ts
  src/modules/chat/entities/message-read.entity.ts
  src/modules/chat/entities/message.entity.ts
  src/modules/events/events.gateway.ts
  src/modules/events/events.module.ts
  src/modules/users/user.entity.ts
Labels: enhancement, feature
