Repository ZenBit-Tech/code-lions_be, pull requests merged in 2024-08, with the labels that each got.

#36 Chat improvements
  src/config/index.ts
  src/interceptors/file-upload/chat-upload.inteceptor.ts
  src/mocks/mock-product.ts
  src/modules/chat/chat-content.enum.ts
  src/modules/chat/chat.controller.ts
  src/modules/chat/chat.service.ts
  src/modules/chat/dto/chat-user.dto.ts
  src/modules/chat/dto/message-response.dto.ts
  src/modules/chat/dto/send-message.dto.ts
  src/modules/chat/entities/message.entity.ts
  src/modules/events/events.gateway.ts
  src/modules/users/dto/user-status-response.dto.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.service.ts
Labels: documentation, enhancement, feature

#34 Feat/order
  src/app.module.ts
  src/common/errors.ts
  src/config/index.ts
  src/mocks/mock-product.ts
  src/modules/orders/dto/address.dto.ts
  src/modules/orders/dto/create-order.dto.ts
  src/modules/orders/dto/get-buyer-order.dto.ts
  src/modules/orders/dto/order-response.dto.ts
  src/modules/orders/dto/order.dto.ts
  src/modules/orders/dto/product.dto.ts
  src/modules/orders/entities/buyer-order.entity.ts
  src/modules/orders/entities/order-status.enum.ts
  src/modules/orders/entities/order.entity.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.module.ts
  src/modules/orders/orders.service.ts
  src/modules/products/entities/product.entity.ts
  src/modules/users/user.entity.ts
Labels: enhancement

#38 fix: fixed to message response
  src/modules/chat/chat.service.ts
Labels: hotfix

#33 Feat/stripe payment
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/common/errors.ts
  src/config/index.ts
  src/main.ts
  src/modules/cart/cart.module.ts
  src/modules/cart/cart.service.ts
  src/modules/orders/dto/create-order.dto.ts
  src/modules/orders/entities/buyer-order.entity.ts
  src/modules/orders/entities/order.entity.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
  src/modules/products/products.service.ts
  src/modules/products/utils/mapProducts.ts
  src/modules/stripe/dto/payment.dto.ts
  src/modules/stripe/stripe.controller.ts
  src/modules/stripe/stripe.interfaces.ts
  src/modules/stripe/stripe.module-definition.ts
  src/modules/stripe/stripe.module.ts
  src/modules/stripe/stripe.service.ts
  src/modules/users/best-vendors.controller.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
Labels: feature

#41 feat: created endpoint to return sorted orders to vendor
  src/common/errors.ts
  src/config/index.ts
  src/modules/orders/dto/orders-count-response.dto.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
Labels: enhancement

#42 Added orderId for review creation
  src/common/errors.ts
  src/modules/reviews/dto/create-review.dto.ts
  src/modules/reviews/review.entity.ts
  src/modules/reviews/reviews.module.ts
  src/modules/reviews/reviews.service.ts
Labels: enhancement

#35 created follow-vendor dto and controller / updated user entity / crea…
  src/common/errors.ts
  src/mocks/mock-product.ts
  src/modules/users/dto/follow-request.dto.ts
  src/modules/users/follow.controller.ts
  src/modules/users/follow.service.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.module.ts
Labels: feature

#45 Feat/stripe onboarding
  .env.example
  .eslintrc.js
  src/common/errors.ts
  src/filters/http-exception.filter.ts
  src/interceptors/file-upload/file-upload.interceptor.ts
  src/mocks/mock-product.ts
  src/modules/products/products.service.spec.ts
  src/modules/products/products.service.ts
  src/modules/stripe/dto/account-link-response.dto.ts
  src/modules/stripe/stripe.controller.ts
  src/modules/stripe/stripe.service.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.service.ts
Labels: feature

#39 Feat/single order endpoints
  src/common/errors.ts
  src/modules/orders/dto/single-order-response.dto.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
Labels: documentation, feature

#46 Added try catch blocks for chat and event methods
  src/common/errors.ts
  src/modules/chat/chat.service.ts
  src/modules/events/events.gateway.ts
Labels: chore

#44 Profile settings
  src/common/decorators/get-user.ts
  src/common/errors.ts
  src/mocks/mock-product.ts
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/mailer/templates/change-email.hbs
  src/modules/mailer/templates/change-password.hbs
  src/modules/users/user.entity.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
Labels: documentation, enhancement, feature

#49 Feat/stripe transfers
  .env.example
  src/common/errors.ts
  src/modules/chat/dto/create-chat.dto.ts
  src/modules/mailer/mailer.service.ts
  src/modules/mailer/templates/stripe-error.hbs
  src/modules/stripe/stripe.controller.ts
  src/modules/stripe/stripe.module.ts
  src/modules/stripe/stripe.service.ts
  src/modules/users/users.service.ts
Labels: feature

#47 Feat/notifications
  src/app.module.ts
  src/common/errors.ts
  src/mocks/mock-product.ts
  src/modules/cart/cart.service.ts
  src/modules/events/events.gateway.ts
  src/modules/events/events.module.ts
  src/modules/notifications/dto/create-notification.dto.ts
  src/modules/notifications/dto/notification-response.dto.ts
  src/modules/notifications/entities/notification-type.enum.ts
  src/modules/notifications/entities/notification.entity.ts
  src/modules/notifications/notifications.controller.ts
  src/modules/notifications/notifications.module.ts
  src/modules/notifications/notifications.service.spec.ts
  src/modules/notifications/notifications.service.ts
  src/modules/orders/dto/create-order.dto.ts
  src/modules/orders/entities/order-status.enum.ts
  src/modules/orders/entities/order.entity.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
  src/modules/products/dto/product-response.dto.ts
  src/modules/products/products.service.ts
  src/modules/users/user.entity.ts
  src/modules/users/users.service.ts
  src/modules/wishlist/wishlist.service.ts
Labels: enhancement

#50 Adjusted ptofile settings
  src/modules/auth/auth.controller.ts
  src/modules/auth/auth.service.ts
  src/modules/notifications/notifications.service.ts
  src/modules/users/users.controller.ts
  src/modules/users/users.service.ts
Labels: enhancement, chore

#48 Get and update application fee
  src/common/errors.ts
  src/modules/stripe/dto/update-application-fee.dto.ts
  src/modules/stripe/entities/stripe.entity.ts
  src/modules/stripe/stripe.controller.ts
  src/modules/stripe/stripe.module.ts
  src/modules/stripe/stripe.service.ts
Labels: feature

#51 Feat/update order status
  .eslintrc.js
  src/common/errors.ts
  src/modules/mailer/templates/received-order.hbs
  src/modules/mailer/templates/reject-order.hbs
  src/modules/mailer/templates/sent-back-order.hbs
  src/modules/mailer/templates/sent-order.hbs
  src/modules/orders/entities/order.entity.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.module.ts
  src/modules/orders/orders.service.ts
  src/modules/stripe/stripe.module.ts
  src/modules/stripe/stripe.service.ts
Labels: feature

#55 Fix/backend fixes
  src/common/errors.ts
  src/modules/auth/auth.service.ts
  src/modules/orders/dto/single-order-response.dto.ts
  src/modules/orders/orders.module.ts
  src/modules/orders/orders.service.ts
Labels: bug

#52 fix/notifications
  src/common/errors.ts
  src/common/utils/getClientByUserId.ts
  src/modules/chat/chat.module.ts
  src/modules/events/events.gateway.ts
  src/modules/events/events.module.ts
  src/modules/notifications/dto/create-notification.dto.ts
  src/modules/notifications/dto/notification-response.dto.ts
  src/modules/notifications/entities/notification-type.enum.ts
  src/modules/notifications/notifications.service.ts
  src/modules/orders/orders.module.ts
  src/modules/orders/orders.service.ts
  src/modules/reviews/reviews.module.ts
  src/modules/reviews/reviews.service.ts
  src/modules/users/users.module.ts
  src/modules/users/users.service.ts
Labels: enhancement

#57 Feat/stripe overdue
  src/common/errors.ts
  src/config/index.ts
  src/modules/auth/auth.guard.ts
  src/modules/auth/public.decorator.ts
  src/modules/orders/orders.controller.ts
  src/modules/orders/orders.service.ts
  src/modules/products/products.controller.ts
  src/modules/stripe/dto/overdue-payment.dto.ts
  src/modules/stripe/stripe.controller.ts
  src/modules/stripe/stripe.service.ts
  src/modules/users/users.controller.ts
Labels: enhancement, feature
